version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitData:/etc/rabbitmq/
      - rabbitEtc:/var/lib/rabbitmq/
      - rabbitLogs:/var/log/rabbitmq/
    networks:
      - app-tier
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  data01:
    driver: local
  rabbitData:
    driver: local
  rabbitEtc:
    driver: local
  rabbitLogs:
    driver: local

networks:
  elastic:
    driver: bridge
  app-tier:
    driver: bridge